//prefix, suffix, description
function randomWeapon() {
    var name = ""
    var bodyText = ""

    var weaponSuffix = false;
    if (Math.random() < .4) {
        weaponSuffix = true;
    }
    var first = getRand(weaponEffects)
    name += first[0] + " " + toTitleCase(getRand(weapons))
    bodyText += first[2]

    if (weaponSuffix) {
        var second = getRand(weaponEffects)
        //prevent intersections
        while (second[0] === first[0]){
            second = getRand(weaponEffects)
        }
        name += " " + second[1]
        bodyText += "<br>" + second[2]
    }

    $("#outcome-title").html(name)
    $("#outcome-text").html(bodyText)
}
var weaponEffects = [
    ["Returning", "of Calling", "The owner of this weapon can summon it to their hand as long as it's less than 60 feet from them. This weapon can be drawn as a bonus action."],
    ["Invisible", "of Hiding", "The bearer can draw this weapon as a bonus action. This weapon cannot be seen by the naked eye. If dropped, finding it takes a Perception check against a DC of 15."]
    ["Blood", "of Bleeding", "+1 to attack rolls. On a critical hit, the bearer of this weapon bleeds from a random orifice for 1d4 damage."],
    ["Cold 'n' Sweaty", "of Cold Sweats", "On a critical failure, this weapon slips out of the user's grasp."],
    ["Stupefying", "of stupidity", "On a hit, the INT score of the afflicted drops by 1d4 for 1d6 hours. On a critical miss, the user is affected instead."],
    ["Adamantine", "of Adamantine", "This item is indestructible."],
    ["Alien", "of Lunacy", "Once attuned, the bearer constantly hears the ongoing, utterly insane mutterings of an alien intelligence trapped inside this weapon. Should this weapon be destroyed, the being will be released."],
    ["Ancient", "of Old", "This worn weapon inscribed with ancient runes can be used as a Spellcasting Focus."],
    ["Antikytheran", "of Mechanisms", "An ancient mechanism is housed within this weapon that never configures the same way twice. Once per long rest the bearer can spend one minute to attempt a DC 20 investigation check to configure the device. If successful, the weapon becomes a +1 weapon until the end of the next long rest."],
    ["Arcane", "of Arcana", "This weapon can project a spectral tome suspended in mid-air that the bearer can interact with like a physical book. This tome can be used as a spellbook and may contain some spells from its previous bearer."],
    ["Arctic", "of Snow", "Icy wind and snowflakes bluster around this weapon, even in warm environments. The bearer can walk on the surface of the lightest snow, leaving no footprints."],
    ["Artist's", "of the Artist", "The bearer may use this weapon to make colored marks on any surface. The marks will fade away in 24 hours."],
    ["Assassin's", "of the Assassin", "The bearer may add 1d4 poison damage to all attacks made during surprise rounds."],
    ["Autumn", "of Falling Leaves", "The weapon contains a resevoir of natural magic that can a sustain a cascade of falling leaves for up to 30 seconds. The bearer may use an action to plant this weapon in the ground and release this magic. While planted and undepleted, creatures within 10 feet of this weapon have half cover. A long rest restores 1d6 sconds of energy to the weapon's resevoir."],
    ["Barbed", "of Barbs", "After an attack roll, the bearer may use their reaction to add 1d4 to the damage roll and take 1d4 damage."],
    ["Binding", "of Binding", "When you hit a creature with this weapon, the ground beneath binds to its feet, slowing its speed by 5 feet until the end of its next turn. This has no effect on creatures that are flying or swimming."],
    ["Blasted", "of Detonation", "The bearer may use a bonus action to activate destructive magic within this weapon. It begins to glow with white-hot intensely, and at the beginning of the bearer's next turn, the weapon casts a level 1 Shatter spell (DC 12) centered on the weapon. The weapon then loses this property."],
    ["Blessed", "of Parables", "Whenever the bearer of this item receives magical healing from a spell on the Cleric’s spell list, they gain an additional amount of hit points equal to their Wisdom (Religion) skill."],
    ["Blind", "of Eyes", "Garrish eyes are painted on this weapon. The bearer can use an action to see/unsee through the eyes, even if their own senses are compromised."],
    ["Blithe", "of Mirth", "The bearer is filled with inexplicable joy. All charisma skill and saving throw rolls gain a +1 bonus, but all wisdom skill and saving throw rolls gain a -1 penalty."],
    ["Bloodthirsty", "of Bloodthirst", "The bearer of this weapon spend a bonus action and a hit die to turn this weapon into a +1 magic weapon for 1d4 turns."],
    ["Bonded", "of Twins", "This item is part of a pair of identical items. The bearer of either knows the location of the other at all times."],
    ["Booming", "of Thunder", "The bearer may choose to deal Thunder damage with this weapon and gain a +1 bonus to damage."],
    ["Braided", "of Knots", "The bearer may use their action to cause the weapon to become a 50 ft length of hemp rope at will."],
    ["Deep", "of the Deep", "The bearer can hold their breath for 5 minutes before the onset of asphyxiation."],
    ["Broken", "of Shards", "This weapon is badly damaged. It is a testament to its former power that it is still serviceable. If reforged, it might regain its former power."],
    ["Capricious", "of Chance", "If the weapon is attuned to a Chaotic aligned character, they may roll a die after completing a long rest. If the result was an even number, treat this as a +1 magic weapon until they finish a long rest."],
    ["Cardinal", "of the Lodestone", "The bearer always knows which way is north and has advantage on Wisdom (Survival) checks for land navigation."],
    ["Caustic", "of Corrosion", "The bearer may choose to deal Acid damage with this weapon and gain a +1 bonus to damage."],
    ["Chained", "of Chains", "The bearer can spend an action to mystically bind or unbind themselves to this weapon. While bound, the bearer can no longer be disarmed but cannot switch out or throw this weapon."],
    ["Captivating", "of Saving Graces", "While the bearer is at 0 hp, they begin to hear the most beautiful music they have ever heard. The bearer has advantage on death saving throws and cannot recall details about the music if they wake."],
    ["Charged", "of Lightning", "The bearer may choose to deal Lightning damage with this weapon and gain a +1 bonus to damage."],
    ["Chill", "of Chills", "The air around the bearer of this weapon is always unnaturally cold. One's breath becomes visible, and frost continually forms on the surface of the bearer's hair, weapons, and armor. The bearer suffers no ill effect from being in extremely cold environments."],
    ["Civilized", "of the Capital", "The bearer gains +1 to intelligence saving thows."],
    ["Compassionate", "of Compassion", "Wounds inflicted with this weapon cause no pain."],
    ["Consecrated", "of Consecration", "Treat as a +1 magic weapon when attacking Undead. Any creature slain with this weapon cannot be raised as undead."],
    ["Corrosive", "of Dissolving", "When the bearer hits a creature with this weapon, they may deal their proficiency bonus in acid damage to a different creature within 5 feet of the target."],
    ["Courser's", "of the Hostler", "The bearer can placate and calm any mount not under the influence of a spell or possession."],
    ["Crashing", "of the Crashing Waves", "Whenever the bearer deals damage to a hostile creature, this weapon gains a charge. As a bonus action, the bearer can use any number of charges to deal that much extra lightning damage on their next attack. If a round (6 seconds) goes by and the weapon has not struck a foe, it loses all charges."],
    ["Crawling", "of Vermin", "The crawling things of the earth, such as insects, snakes, and vermin, are attracted to this item. When placed on the ground, such creatures will scurry toward the item like moths drawn to the flame."],
    ["Cruel", "of Cruelty", "The bearer may re-roll damage from critical hits scored with this weapon and take the second result."],
    ["Dancing", "of Strings", "The bearer may spend an action to permanently animate this weapon. Use the Flying Sword stat block from the Monster Manual p. 20. Also, the weapon retains any other magical properties. Once the animated weapon is reduced to 0 hp or unattuned, the weapon shatters like glass."],
    ["Dark", "of Darkness", "The bearer may choose to deal Necrotic damage with this weapon and gain a +1 bonus to damage."],
    ["Dead", "of Rigor Mortis", "If this weapon is entombed within a corpse for 8 hours, the bearer may treat it as a +1 magic weapon until the end of their next long rest."],
    ["Deceptive", "of Deception", "When the bearer attunes this item, choose a harmless object within sight such as a tea cup, a ball of yarn, or a hairpin. If the bearer is touching the item, they may use an action to transform the weapon in or out of this form."],
    ["Defensive", "of Defense", "Whenever the bearer takes a dodge or disengage action, they may move an additional 5 feet that round."],
    ["Delver's", "of the Delver", "While underground, the bearer of this item always knows the item's depth below the surface and the direction to the nearest path leading upward."],
    ["Desperate", "of Desperation", "The bearer may use an action to release divine magic within, equivalent to a level 1 Cure Wounds spell being cast on all creatures (friend or foe) within 5 feet of the bearer. The weapon is destroyed and loses all magical properties."],
    ["Diplomatic", "of Diplomacy", "The bearer gains one language proficiency chosen by the DM."],
    ["Draconic", "of Dragons", "Treat as a +1 weapon when attacking Dragons."],
    ["Draining", "of Draining", "When the bearer makes a successful attack with this weapon, they gain 10% of the damage as temporary hit points (round down, minimum of 1)."],
    ["Dreamscribe's", "of the Dreamscribe", "The bearer can read books they are touching while sleeping."],
    ["Drunkard's", "of Taverns", "The bearer always knows the direction to the nearest tavern in a 60 mile radius."],
    ["Dryad's", "of the Dryad", "When the bearer is outdoors, harmless creatures such as squirrels and birds flock to them when they sing songs for a minute or longer."],
    ["Eager", "of Yearning", "The bearer does not require an interaction to draw or sheath this weapon"],
    ["Earthen", "of Rooting", "The bearer of this weapon is firmly rooted to the ground. When standing on solid earth or stone, if an effect would move the bearer against his will the distance is reduced by 5 feet."],
    ["Eastern", "of the East", "The bearer gains +1 to wisdom saving throws."],
    ["Effortless", "of Ease", "This weapon takes only one minute to attune."],
    ["Effulgent", "of Light", "The bearer can use this item to cast the Light cantrip on itself at will. While lit, it deals radiant damage instead of its usual damage type."],
    ["Eidolic", "of Apparitions", "Dark apparitions bound to this weapon haunt the edges of the bearer's peripheral vision, becoming hideously visible to devour the bodies of beings slain by this weapon. Once 666 bodies have been devoured, the apparitions will be released to prey upon our world and the sword becomes a permanent +3 weapon. So far, the weapon has eaten 1d6 x 100 + 3d20 bodies."],
    ["Enchanting", "of the Enchantress", "Treat this as a +1 weapon as long as the bearer is enchanted by a spell from the enchantment school of magic."],
    ["Enervating", "of Inner Strength", "Once per long rest, the bearer may spend one minute contemplating the patterns etched on this weapon's surface and regain 1 expended ki point."],
    ["Epistemological", "of Truth", "The bearer has advantage on investigation checks to see through illusions. In addition the bearer can gains advantage on an Insight check to check if someone is lying and disadvantage on all Deception checks."],
    ["Equanimeous", "of Balance", "When attuned to neutral aligned characters, this weapon has a +1 attack bonus during the day and a +1 damage bonus at night."],
    ["Etched", "of Allegories", "Ancient glyphs adorn the surface of this weapon, telling a story with a moral of the player's chosing (such as \"One good turn deserves another\" or \"United we stand, divided we fall\"). While attuning to this weapon, the glyphs spread across the entire skin of the bearer and the moral of the story becomes a bond trait for this character."],
    ["Fairweather", "of Fairweather", "Treat this as a +1 weapon if the bearer has more than half of their maximum hit points"],
    ["Fatespun", "of Intertwined Fates", "Once per short rest, when the bearer crits with this weapon they gain inspiration."],
    ["Favored", "of the Favored", "Once per long rest, the bearer may roll a saving throw with advantage."],
    ["Feathered", "of Feathers", "The bearer may use their reaction to reduce fall damage by 1d6 until the end of turn. They cannot use this feature again until completing a long rest."],
    ["Final", "of Last Hope", "The bearer may spend an action beseaching the spirits within this weapon. Roll a DC 20 Persuasion check or make a sufficiently impassioned plea. If successful, the spirits will sacrifice themselves so that for the next minute the next attack with this weapon will be a crit. The weapon then loses this property forever."],
    ["First", "of Speed", "The bearer gains a +1 bonus to initiative rolls. As long as the bearer is first in the initiative order, their speed increases by 5 feet."],
    ["Forgotten", "of the Forgotten", "The bearer may spend an action to attempt to ignite the old magic in this weapon with a DC 13 Charisma check. If successful, treat the weapon as a +1 weapon as long as the bearer maintains concentration on this effect, maximum 10 minutes."],
    ["Friendly", "of Friendship", "Contains 1d4 unreplenishable charges of the Animal Friendship spell (1st level)."],
    ["Frozen", "of Ice", "The bearer may choose to deal Cold damage with this weapon and gain a +1 bonus to damage."],
    ["Furious", "of Fury", "Treat as a +1 magic weapon when the bearer is raging."],
    ["Ghost-Tipped", "of the Ranks", "Whenever the bearer crits with this weapon, it gains the reach property (10 ft) for 1 minute. If it already had the reach property, increase its reach by 5 ft."],
    ["Ghost-Touched", "of Remembered Glory", "This weapon can be wielded by a missing limb. If so, it becomes a +1 weapon."],
    ["Glorious", "of Glory", "The bearer may choose to change the damage type of weapon to Radiant and its damage roll gains a +1 bonus."],
    ["Goading", "of Duels", "Once per short rest, when the bearer crits with this weapon it casts Compelled Duel on the creature it hit, DC 12."],
    ["Guardian", "of Protection", "When the bearer attunes this weapon they must choose a being in their mind. Henceforth, if the bearer is within 5 feet of the chosen being they may use their reaction to impose disadvantage on an attack roll against that creature. They cannot do this again until they have finished a short or long rest."],
    ["Harkening", "of Eavesdropping", "As long as it is on the same plane of existence, the bearer can hear through this weapon as if they were present."],
    ["Haunted", "of Vengeful Spirits", "Smoke rises from this weapon revealing the apparitions that haunt it. They lash out at living targets every time the bearer scores a hit, doing an additional +2 necrotic damage."],
    ["Healing", "of Healing", "This item contains a healing node. Once per long rest the bearer can use the node and an action to heal 1d4 hit points at touch range."],
    ["Heroic", "of Heroes", "Ancient heroes have wielded this weapon throughout the ages, and their courage still lingers. The bearer has advantage on saving throws vs. fear effects."],
    ["Holy", "of Faith", "When the bearer of this item rolls hit dice, they can choose to re-roll them and take the second result."],
    ["Iconic", "of Symbols", "The weapon is inscribed with holy symbols of the God of the DM's choice. A cleric or paladin that serves that god may use this weapon as a divine focus."],
    ["Imaginary", "of the Imagination", "Once attuned, this weapon exists only in the bearer's imagination until held with intent to do harm. It becomes imaginary again after a short rest."],
    ["Impact", "of Impact", "Once per long rest, the bearer may spend an action to activate an ancient mechanism within the weapon. Gears turn and parts shift as the weapon reconfigures itself into a more menacing version of the original. For 1 minute, attacks made with this weapon ignore resistances (but not immunities)."],
    ["Indifferent", "of Indifference", "The bearer no longer feels emotions. They have immunity to fear effects but disadvantage on Insight and Performance checks, and cannot Rage."],
    ["Indomitable", "of Surging Strength", "When the bearer is grappled by multiple targets, they may choose to break the strongest grapple. If they succeed, then all grapples are broken."],
    ["Inspired", "of Inspiration", "The bearer gains their Constitution modifier in temporary hit points whenever they gain or use inspiration."],
    ["Jagged", "of Teeth", "Once hit by this weapon, the victim cannot regain hit points until the beginning of their next turn."],
    ["Jester's", "of Madness", "Once per short rest, when the bearer crits with this weapon it casts Crown of Madness on the creature it hit, DC 12"],
    ["Leaping", "of Leaping", "Contains 1d4 unreplenishable charges of the Jump spell (1st level)."],
    ["Liar's", "of Lies", "Contains 1d4 unreplenishable charges of the Silent Image spell (1st level)."],
    ["Mage Killer's", "of the Mage Killer", "Ignores the AC bonuses given by spells such as Mage Armor and Shield."],
    ["Malediction", "of Malediction", "Contains 1d4 unreplenishable charges of the Bane spell(1st level)."],
    ["Maligning", "of Maligning", "This weapon does an additional 1d4 damage on attacks of opportunity."],
    ["Marquis'", "of the Maquis", "Once per short rest, when you crit with this weapon it casts Command on its target with the word \"grovel\", DC 12"],
    ["Masked", "of Still Winds", "The bearer and all of their posessions are completely odorless."],
    ["Master's", "of Servants", "Contains 1d4 unreplenishable charges of the Unseen Servant spell (1st level)."],
    ["Meadowforged", "of the Meadow", "A gentle kaleidoscope of butterflies always accompanies this weapon. The bearer has advantage on persuasion checks with Fae creatures less than CR 3."],
    ["Memorial", "of Memories", "When the bearer kills a monster with this weapon, treat this weapon as a +1 weapon whenever you fight another monster of this kind. When the weapon is unattuned, it loses its memory."],
    ["Mimicking", "of Mimicry", "When the bearer places this weapon beside another melee weapon for 1 minute, this weapon changes weapon type, size, and physical qualities to become an exact replica of the other weapon. It does not gain any of the other weapon's magical properties."],
    ["Mindscour", "of Countermeasures", "This weapon disrupts all telepathic communication within 20 feet. Psychic attacks are not affected."],
    ["Mind's Eye", "of the Mind's Eye", "The bearer may choose to deal Psychic damage with this weapon and gain a +1 bonus to damage"],
    ["Mortuary", "of the Mortal Coil", "The bearer's vital signs, such as a pulse and breathing, are masked by this weapon and are undetectable by non-magical inspection."],
    ["Mourner's", "of Last Words", "Contains one charge of the Speak With Dead spell. It regains the charge when the bearer dies."],
    ["Murderous", "of Slaughter", "When the bearer reduces a creature to zero hit points they may use a bonus action to move half their movement speed towards another hostile creature."],
    ["Northern", "of the North", "The bearer gains +1 to constitution saving throws"],
    ["Nourishing", "of Comfort", "Once per long rest, the bearer may lay this weapon beside a bowl of water. After a moment, the bowl of water will begin to boil and after a minute it will transform into a hot meal of special significance to the bearer (Their mother's noodle soup or father's elk stew). Eating this delicious meal is so satisfying that it counts as nourishment for an entire day and restores 1d4 hit points. To anyone other than the bearer, the bowl and its contents appears unchanged."],
    ["Nullifying", "of Nullification", "Any spell of 1st level or lower that includes the bearer as a target has a 10% chance to fail, cast by both friendly and enemy spellcasters."],
    ["Painstrike", "of Pain", "Treat this as a +1 weapon for 1 minute if the bearer takes 13 or more damage in a single round of combat."],
    ["Parrying", "of Parrying", "The bearer may use their reaction to gain a +1 AC bonus until the end of the turn."],
    ["Patient", "of Patience", "Whenever the bearer readies an action, they have advantage on constitution saving throws to maintain concentration."],
    ["Pernicious", "of the Snake", "The bearer may choose to deal Poison damage with this weapon and gain a +1 bonus to damage."],
    ["Phantom", "of the Phantasm", "Damage inflicted with this weapon leaves no physical sign of injury, such as cuts and bruises, and draws no blood."],
    ["Pious", "of the Pious", "The bearer may spend ten minutes paying honor to the spirits that govern this weapon, shaving their head in tribute. Once the ceremony is finished, it becomes a +1 weapon until the end of the next long rest. They must wait 10 days until they have long enough hair to re-enact this ritual."],
    ["Preacher's", "of the Preacher", "This weapon increases the bearer's Channel Divinity range by 5 feet."],
    ["Force", "of Force", "The bearer may choose to deal Force damage with this weapon and gain a +1 bonus to damage."],
    ["Quantum", "of Uncertainty", "Every time the bearer takes a long rest, this weapon changes in appearance and function. It retains this property but any other properties are lost. However, it gains a new random ability from this chart."],
    ["Quicksilver", "of Quicksilver", "The bearer may use a bonus action to change the form of the weapon to any other simple or martial melee weapon. It always counts as a silvered weapon no matter what form it takes."],
    ["Rainbow", "of Rainbows", "The bearer may change the damage type of a spell they cast once per long rest."],
    ["Refined", "of Quality", "This weapon is so finely constructed it never needs maintenance, cannot rust or tarnish, and gains a +1 to damage rolls."],
    ["Reliable", "of Reliance", "When attacking with this weapon, crit fails (rolling 1) on attack rolls do not automatically miss the target."],
    ["Renaissance", "of the Renaissance", "Once per long rest, the bearer may gain +1 to any skill check."],
    ["Resonant", "of Resonance", "The bearer can spend an action and 1 ki point to treat this as a +1 weapon for 1 minute."],
    ["Restrained", "of Subdual", "This weapon only deals non-lethal damage to living targets"],
    ["Righteous", "of Righteousness", "Treat this as a +1 weapon during the day when attuned to a good aligned character."],
    ["Rosen", "of Roses", "A ruby worth 30gp is the center stone in a rose-shaped setting on the weapon. If the bearer removes the ruby, the weapon grows a new one at the end of the month. The weapon always smells of roses while the ruby is in its setting."],
    ["Runic", "of Runes", "Whenever bearer casts a spell, treat this weapon as a +1 weapon until the beginning of their next turn."],
    ["Scarlet", "of Bleeding", "This weapon perpetually drips the blood of a monstrous race, chosen by the DM. The bearer can speak that race's language and has advantage on intimidation checks against monsters of that race when the weapon is revealed."],
    ["Siege", "of Sieges", "This weapon does maximum damage against man-made, inanimate objects."],
    ["Shading", "of Shade", "The bearer suffers no harm or discomfort in temperatures as high as 120 degrees Fahrenheit."],
    ["Shadow", "of Shadows", "Treat as a +1 magic weapon when in dim light."],
    ["Shamanic", "of Rituals", "Whenever the bearer is casting a spell as a ritual, they have advantage to maintain concentration during the ritual."],
    ["Shaming", "of Disgrace", "Any humanoid creature hit with this weapon loses all of the hair on their head and face."],
    ["Shielding", "of Shielding", "This item contains 1d4 unreplenishable charges of the Shield spell."],
    ["Skyward", "of Unusual Gravity", "This weapon falls up instead of down. Its weight does not contribute towards encumberance."],
    ["Slayer's", "of Slaying", "Treat as a +1 weapon when attacking Demons and Devils."],
    ["Smoldering", "of Flame", "The bearer may choose to deal Fire damage with this weapon and gain a +1 bonus to damage."],
    ["Smuggler's", "of Smuggling", "This weapon contains a small, secret compartment. A character must succeed on a DC 20 Wisdom (Perception) check to reveal the compartment when searching the bearer."],
    ["Sojourner's", "of the Sojourner", "A poem, story, or map that describes a long-forgotten treasure that will make this weapon more powerful is etched on the surface of the weapon."],
    ["Solemn", "of Solemnity", "The bearer may spend an action to stabilize a dying creature within 5 feet. They cannot do so again until they have completed a long rest."],
    ["Soulbound", "of Imprisonment", "A powerful malevolent being is bound within this weapon and it will be released upon the weapon's destruction."],
    ["Southern", "of the South", "The bearer gains +1 to dexterity saving throws."],
    ["Spring", "of Spring Rain", "The weapon contains a pool of healing energy that can restore up to 30 hp. The bearer may use an action to plant this weapon in the ground and release this energy. While planted and undepleted, creatures that end their turn within 10 feet of the weapon are showered in warm rain that restores 1 hp per round. A long rest restores 1d6 hp of energy to the weapon's pool."],
    ["Staunch", "of Security", "Anyone except the bearer must attempt a DC 10+x Charisma check to pick up this weapon, where x is the bearer's level. Any attack made with this weapon against the bearer has disadvantage."],
    ["Strange", "of the Far Realm", "Treat this as a +1 weapon when attacking Aboleths and other creatures from the Far Realm"],
    ["Strapping", "of the Undaunted", "Whenever the bearer breaks a grapple, they may choose to push the grappler up to 10 feet away from them as a bonus action."],
    ["Striding", "of Strides", "Contains 1d4 unreplenishable charges of the Longstrider spell (1st level)."],
    ["Summer", "of the Scorching Sun", "The weapon contains a resevoir of scorching light that can deal up to 30 hp of radiant damage. The bearer may use an action to plant this weapon in the ground and release this energy. While planted and undepleted, creatures that end their turn within 10 feet of the weapon are brightly illuminated and seared for 1 radiant damage per round. A long rest restores 1d6 hp of energy to the weapon's resevoir."],
    ["Surgeon's", "of the Surgeon", "The bearer may use a bonus action to gain advantage to Wisdom (Medicine) checks for the rest of the turn."],
    ["Swift", "of Reflexes", "If the bearer is first in the initiative order, they may treat this as a +1 weapon."],
    ["Tenacious", "of the Tenacious", "When the bearer takes a long rest, they gain back one additional hit die."],
    ["Tithing", "of Tithes", "The bearer may lay 10 gold coins along the surface of the weapon and pray to a God of their choice for 10 minutes. At the end of this ritual, the weapon becomes a +1 weapon until the next long rest and the 10 gold coins are permanently gone. This boon will be lost if the bearer acts in a way that is contradictory to that deity's teachings."],
    ["Transient", "of the Breaking Seal", "Over the course of a long rest, the bearer may transfer the other magic properties of this weapon to a melee weapon of their choosing. This weapon then loses those properties."],
    ["Translucent", "of Translucence", "The bearer gains an extra level one spell slot, which recovers only after a full moon rises."],
    ["Trusty", "of Resurgence", "Treat this as a +1 weapon if the bearer has half their maximum hit points or less."],
    ["Tsunami", "of Crashing Waves", "Once per short rest, when the bearer crits with this weapon, all creatures other than the bearer within 5 feet of the target (including the target) must roll a DC 12 constitution saving throw or be knocked prone by a wave of concussive force."],
    ["Twilight's", "of the Setting Sun", "Once per short rest, when you crit with this weapon it casts Hex on the target. Roll a d6 to determine which of the target's attributes is weakened. The bearer cannot transfer the curse to another creature."],
    ["Unity", "of Unity", "Whenever the bearer of this weapon takes a help action in combat, the aided ally may treat their weapon as a +1 magic weapon until the end of their next turn."],
    ["Victorious", "of Victory", "Whenever the bearer kills a creature with this weapon, they gain temporary hit points equal to the creature's CR (minimum of 1)."],
    ["Vigilant", "of Vigilance", "The bearer gains +1 to their Passive Perception."],
    ["Vile", "of Villains", "Treat this as a +1 weapon at night when attuned to an evil aligned character."],
    ["Violent", "of Violence", "Everytime you crit with this weapon, it gains 1 charge. As a bonus action, use a charge to make this a +1 weapon for 1 minute. All charages are lost at the end of a long rest."],
    ["Visionary", "of the Visionary", "The weapon does an additional 1 elemental damage based on the color of the bearer's eyes: (amber: lightning, black: necrotic, blue: cold, brown: acid, green: force, gray: thunder, hazel: poison, purple: psychic, red: fire, white: radiant)"],
    ["Vital", "of Vitality", "The bearer's maximum hit points increases by their constitution modifier while attuned to this item. These hit points are lost when the bearer unattunes the item."],
    ["Voidstone", "of the Void", "This weapon cannot be detected by the \"Detect Magic\" spell unless the caster touches the weapon."],
    ["Voltaic", "of Conduits", "Whenever the bearer deals damage to a creature, this weapon gains a charge. As a bonus action, the bearer can use any number of charges to deal that much extra lightning damage on their next attack. If a round (6 seconds) goes by and the weapon has not struck a foe, it loses all charges."],
    ["War Leader's", "of the War Leader", "The bearer can use an action to amplify their voice three times louder than normal."],
    ["Warded", "of Warding", "Once per long rest the bearer may draw a 20 foot line in the ground with this weapon that lasts for 1 minute. The Undead must succeed on a DC 12 wisdom saving throw to move across this line. If they fail, they cannot move again until their next turn."],
    ["Waterborne", "of the Sea", "The item floats on water or other liquids. Its bearer has advantage on Strength (Athletics) checks to swim."],
    ["Weave-touched", "of the Weave", "Whenever the bearer casts a spell, this weapon gains charges equal to the spell's level. The bearer can use a bonus action to remove 13 charges and make this a +1 weapon until the start of the next round. All charges are lost during a long rest."],
    ["Western", "of the West", "The bearer gains +1 to charisma saving throws."],
    ["Wild", "of the Wilds", "The bearer gains +1 to strength saving throws."],
    ["Winged", "of Wings", "Once per long rest, the bearer may use an action to transform this weapon into a magical raven that can deliver a message to anyone in a 50 mile radius, provided the bearer knows their name and face. When the raven returns, it reverts into its weapon form. If the bird should die en route, it reverts into weapon form and unattunes from the bearer."],
    ["Winter", "of Winter Ice", "The weapon contains a resevoir of ice magic that can a freeze the ground for up to 30 seconds. The bearer may use an action to plant this weapon in the ground and release the ice magic within. While planted and undepleted, the ground in a 10 foot radius of this weapon becomes difficult terrain. A long rest restores 1d6 seconds of energy to the weapon's resevoir."],
    ["Woodsman's", "of Felling", "This weapon does maximum damage against plant creatures."],
    ["Zen", "of Zen", "Treat this as a +1 weapon for 1 minute after meditating with it for 1 minute."],
]
var weapons = [
	"amputation knife",
	"club",
	"dagger",
	"bayonet",
	"bonesaw",
	"brass knuckles",
	"darts", "needle", "scythe", "sickle", "stiletto", "cutlass", "epee", "rapier",
	"estoc", "axe", "cane", "pickaxe", "whip", "hammer", "crossbow", "chakram",
	"javelin", "handaxe", "greataxe", "sledgehammer",
	"sword", "shank", "claymore", "war pick", "maul", "pike", "spork",
	"longbow",
    "cleaver",
	"arrow",
	"katana",
    "spear",
    "brick",
	"wand",
	"bow",
	"mace",
	"club",
	"flail",
	"knife",
	"fork",
	"spoon",
	"meat hook"
]
