var item1 = [
	"Spooky",
	"Unsettling",
	"Invisible",
	"The",
	"Talking",
	"Glowing",
	"Shining",
	"Unremarkable",
	"Gaudy",
	"Tiny",
	"Terrifying",
	"Singing",
	"Spinning",
	"Holy",
	"Unsettling",
	"Invisible",
	"Misfiring",
    "Arcane",
    "Celestial",
    "Intelligent",
    "Multidimensional",
    "Cleansing",
]

var item2 = [
	"amputation knife",
	"club",
	"dagger",
	"bayonet",
	"bonesaw",
	"brass knuckles",
	"darts", "needle", "scythe", "sickle", "stiletto", "cutlass", "epee", "rapier",
	"estoc", "axe", "cane", "pickaxe", "whip", "hammer", "crossbow", "chakram",
	"javelin", "handaxe", "greataxe",
	"sword",
	"arrow",
	"shield",
	"arrow",
	"katana",
    "spear",
    "brick",
	"wand",
	"bow",
	"mace",
	"club",
	"flail",
	"knife",
	"fork",
	"spoon",
	"meat hook"
]

var item3 = [
	"hurting",
	"lust",
	"rage",
	"confusion",
	"mind control",
	"hallucinations",
	"pain",
	"stupidity",
	"unbelievable fertility",
	"cold sweats",
	"terror",
    "despair",
    "air",
    "blood",
    "meat",
    "discord",
    "healing",
    "dread",
    "paralysis",
    "drowsiness", "+2 attack", "+2 damage", "+1 attack", "+1 damage"
]
